config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home_pages#home'

  root "session#new"
	
	get 'pages/home'

	get 'login' => 'session#new'
	get 'alert_type' => 'pages#alert_type'
	get 'alert' => 'pages#alert'

	get 'alert_message' => 'pages#alert_message'

	get  'signup' => 'accounts#new'
	post 'signup' => 'accounts#create'

	get     'login' => 'session#new'
	post    'login' => 'session#create'
	delete  'logout' => 'session#destroy'

  get 'deactivate' => 'home_pages#deactivate'
	get 'activate' => 'home_pages#activate'

	get 'test_button' => 'pages#set_alert_test'
	get 'live_button' => 'pages#set_alert_live'
	get 'landslide_button' => 'pages#set_landslide_type'
	get 'flashflood_button' => 'pages#set_flashflood_type'
	get 'tsunami_button' => 'pages#set_tsunami_type'
	get 'missile_button' => 'pages#set_missile_type'
  get 'create_alert'  => 'pages#create_alert'

  get 'redo_type' =>  'pages#wipe_alert_type'
	get 'redo_emergency' => 'pages#wipe_emergency_type'

	get 'reset_app' => 'application#reset_app'
	get 'back_home' => 'application#back_to_home'

	get 'generate_message' => "pages#generate_message"
  get 'parse_comments' => "pages#parse_comments"
  post 'parse_comments' => "pages#parse_comments"

	resources :accounts
	resources :alerts
	resources :locations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new
    puts "____DATABASE_CHECK____"
    Alert.all.each do |alert|
      puts alert.id
    end
    cookies.delete :username
    cookies.delete :alert
    cookies.delete :emergency
    cookies.delete :message
    cookies[:locations] = " "
  end

	def create
		$current_user = ""

		account = Account.find_by(username: params[:session][:username])
		if account && account.authenticate(params[:session][:password])
			# log in
			cookies[:username] = account.username
			redirect_to home_path
		else
			redirect_to login_path
		end
	end

	def destroy
	end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/views/session/new.html.erb
<h1 style="color: white">Hippopotamus Alert System</h1>
<div style="padding-left: 318px;">
<div class="jumbotron" style="padding-bottom: 100px; padding-top: 30px; width: 500px;">
			<h3 style="text-align: center">Sign In</h3>
    <%= form_for(:session, url: login_path) do |f| %>
      <%= f.label :username %>
      <%= f.text_field :username, class: 'form-control input-sm chat-input' %>
      <%= f.label :password %>
      <%= f.password_field :password, class: 'form-control' %>
			<div class="wrapper">
      	<span class="group-btn pull-left">
					<%= f.submit "Sign In", class: 'btn btn-primary btn-md', style: 'margin-top: 5%' %>
				</span>
			</div>
      <div class="wrapper">
              <span class="group-btn pull-right">
                <%= link_to "Sign Up", signup_url, class: 'btn btn-primary btn-md', style: 'margin-top: 5%' %>
              </span>
      </div>
    <% end %>
</div>
</div>