config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home_pages#home'

  root "session#new"
	
	get 'pages/home'

	get 'login' => 'session#new'
	get 'alert_type' => 'pages#alert_type'
	get 'alert' => 'pages#alert'

	get 'alert_message' => 'pages#alert_message'

	get  'signup' => 'accounts#new'
	post 'signup' => 'accounts#create'

	get     'login' => 'session#new'
	post    'login' => 'session#create'
	delete  'logout' => 'session#destroy'

  get 'deactivate' => 'home_pages#deactivate'
	get 'activate' => 'home_pages#activate'

	get 'test_button' => 'pages#set_alert_test'
	get 'live_button' => 'pages#set_alert_live'
	get 'landslide_button' => 'pages#set_landslide_type'
	get 'flashflood_button' => 'pages#set_flashflood_type'
	get 'tsunami_button' => 'pages#set_tsunami_type'
	get 'missile_button' => 'pages#set_missile_type'
  get 'create_alert'  => 'pages#create_alert'

  get 'redo_type' =>  'pages#wipe_alert_type'
	get 'redo_emergency' => 'pages#wipe_emergency_type'

	get 'reset_app' => 'application#reset_app'
	get 'back_home' => 'application#back_to_home'

	get 'generate_message' => "pages#generate_message"
  get 'parse_comments' => "pages#parse_comments"
  post 'parse_comments' => "pages#parse_comments"

	resources :accounts
	resources :alerts
	resources :locations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/pages/alert.html.erb
<h1 style="color: white;"> <%= cookies[:alert] %> Alert</h1>

<div class="jumbotron">
  <%= link_to "Landslide", landslide_button_path, class: "btn btn-primary btn-lg btn-block"%>

  <%= link_to "Flash flood", flashflood_button_path, class: "btn btn-primary btn-lg btn-block"%>

  <%= link_to "Tsunami", tsunami_button_path, class: "btn btn-primary btn-lg btn-block"%>

  <%= link_to "Ballistic missile", missile_button_path, class: "btn btn-primary btn-lg btn-block"%>

	<div style="padding-top: 5px;">
	<%= link_to redo_type_path, class: "btn btn-primary btn-lg" do %>Back<% end %>
	</div>

</div>

<!--<span class="group-btn">
	<%= link_to "Review alert", alert_message_path, class: "btn btn-primary pull-right"%>
</span>-->

app/views/pages/alert_message.html.erb
<h1 style="color: white;"> <%= cookies[:alert] %> Alert</h1>

<script>

    function myFunction() {
        let messagelocations = $('.form-control').val();
        messagelocations = messagelocations.join(', ') + " ";
        document.getElementById('myform_comments').value = messagelocations;
    }

</script>
<div class="jumbotron">
  <div class="row">
    <div class="form-group">
      <label for="exampleFormControlSelect2">Affected Area</label>
      <select multiple name="location[]" size="20" class="form-control" id="exampleFormControlSelect2">
        <% $locations.each do |location| %>
          <option value="<%= location.location %>"><%= location.location %></option>
        <% end %>
      </select>
    </div>
    <div class="col-md-6">
      <label for="exampleFormControlSelect2">Areas Selected</label>
      <textarea rows="4" cols="55" readonly><%= cookies[:locations] %></textarea>
    </div>
    <div>
      <%= form_tag :action => 'parse_comments' do %>
        <%= text_area :myform, :comments, :cols => '0', :rows => '0', :class => 'invisible' %>
            <button type="submit" class="btn btn-primary pull-right" onclick="myFunction()">Select Areas</button>
        <% end %>
    </div>
  </div>
  </br>
  </br>
  </br>

  <form action="create_alert">
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Alert Message</label>
        <textarea name="message" class="form-control" id="exampleFormControlTextarea11" rows="6"><%= cookies[:message] %></textarea>
      </div>

    <div class="btn-toolbar">
      <!--TESTING-->
      <%= link_to "Generate Message", generate_message_path, :class => 'btn btn-primary'%>
      <!--TESTING-->
      <button type="submit" class="btn btn-primary pull-right">Send Alert</button>
    </div>

    <div style="padding-top: 5px;">
      <%= link_to "Back", redo_emergency_path, class: "btn btn-primary" %>
    </div>

  </form>
</div>

app/views/pages/alert_type.html.erb
<h1 style="color: white;">Alert Type</h1>

<div class="jumbotron">
  <%= link_to "TEST Alert", test_button_path, class: "btn btn-primary btn-lg btn-block"%>
  <%= link_to "LIVE Alert", live_button_path, class: "btn btn-danger btn-lg btn-block"%>
	<div style="padding-top: 5px;"><%= link_to home_path, class: "btn btn-primary btn-lg" do %>Back<% end %></div>
</div>