config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'home_pages#home'

  root "session#new"
	
	get 'pages/home'

	get 'login' => 'session#new'
	get 'alert_type' => 'pages#alert_type'
	get 'alert' => 'pages#alert'

	get 'alert_message' => 'pages#alert_message'

	get  'signup' => 'accounts#new'
	post 'signup' => 'accounts#create'

	get     'login' => 'session#new'
	post    'login' => 'session#create'
	delete  'logout' => 'session#destroy'

  get 'deactivate' => 'home_pages#deactivate'
	get 'activate' => 'home_pages#activate'

	get 'test_button' => 'pages#set_alert_test'
	get 'live_button' => 'pages#set_alert_live'
	get 'landslide_button' => 'pages#set_landslide_type'
	get 'flashflood_button' => 'pages#set_flashflood_type'
	get 'tsunami_button' => 'pages#set_tsunami_type'
	get 'missile_button' => 'pages#set_missile_type'
  get 'create_alert'  => 'pages#create_alert'

  get 'redo_type' =>  'pages#wipe_alert_type'
	get 'redo_emergency' => 'pages#wipe_emergency_type'

	get 'reset_app' => 'application#reset_app'
	get 'back_home' => 'application#back_to_home'

	get 'generate_message' => "pages#generate_message"
  get 'parse_comments' => "pages#parse_comments"
  post 'parse_comments' => "pages#parse_comments"

	resources :accounts
	resources :alerts
	resources :locations

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/home_pages_controller.rb
class HomePagesController < ApplicationController
  require 'will_paginate'

	def home

	end
	
  def new
    cookies.delete :alert
    cookies.delete :emergency
    cookies.delete :message
    cookies[:locations] = " "
  end

  def deactivate
    id = params[:id]

    alert = Alert.find_by(id: id)
    alert.status = "DEACTIVATED"
    alert.save

    redirect_to home_path
  end

  def activate
    puts "________________________________________"
    puts "ACTIVATE BUTTON CLICKED"
    id = params[:id]
    puts id

    alert = Alert.find_by(id: id)
    alert.status = "ACTIVE"
    alert.save

    redirect_to home_path
  end

end

app/helpers/home_pages_helper.rb
module HomePagesHelper
end

app/views/home_pages/home.html.erb
<h1 style="color: white">Hippopotamus Alert System</h1>

<div class="jumbotron table-responsive">
  <span class="group-btn">
    <%= link_to "Create New Alert", alert_type_path, class: "btn btn-primary centered"%>
  </span>
  </br>
  </br>
  <div class="table-responsive">
    <table class="table table-hover">
      <thead class="thead-dark">
        <tr class="bg-dark">
          <th>Type</th>
          <th>Emergency</th>
          <!-- <th>Affected Areas</th> -->
          <!-- <th>Message</th> -->
          <th>User</th>
          <th>Created</th>
          <th>Last Updated</th>
        </tr>
      </thead>
      <tbody>
        <% Alert.order(status: :asc, created_at: :asc).each do |alert| %>
          <form action="deactivate">
            <tr>
              <% if alert.status == "ACTIVE" %>
              <td><%= alert.alert_type %></td>
              <td><%= alert.emergency_type %></td>
              <!-- <td><%= alert.affected_areas %></td> -->
              <!-- <td><%= alert.alert_message %></td> -->
              <td><%= alert.user %></td>
              <td><%= alert.created_at %></td>
              <td><%= alert.updated_at %></td>
              <td><%= alert.status %></td>
              <td><button type="submit" class="btn btn-primary btn-sm" style="line-height: 8px; background-color: red" >Deactivate</button></td>
              <td><input type="hidden" name="id" value="<%= alert.id %>" ></td>
              <% end %>
            </tr>
          </form>
        <form action="activate">
          <tr>
            <% if alert.status == "DEACTIVATED" %>
              <td><%= alert.alert_type %></td>
              <td><%= alert.emergency_type %></td>
              <!-- <td><%= alert.affected_areas %></td> -->
              <!-- <td><%= alert.alert_message %></td> -->
              <td><%= alert.user %></td>
              <td><%= alert.created_at %></td>
              <td><%= alert.updated_at %></td>
              <td><%= alert.status %></td>
              <td><button type="submit" class="btn btn-primary btn-sm" style="line-height: 8px; background-color: green" >Activate</button></td>
              <td><input type="hidden" name="id" value="<%= alert.id %>" ></td>
            <% end %>
          </tr>
        </form>
        <% end %>
      </tbody>
    </table>

  </div>
</div>